/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Kaze no Klonoa - Door to Phantomile (Japan Rev 1))
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* confirmed: SYSTEM.CNF / JP Rev 1 EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80036F18u
#define func_80036F18 BootEntry  /* alias */
